const mockLocations = [
  {
    id: "1",
    name: "Warsaw Drift Track",
    latitude: 52.2297,
    longitude: 21.0122,
    created_at: "",
  },
  {
    id: "2",
    name: "Krakow Racing Circuit",
    latitude: 50.0647,
    longitude: 19.945,
    created_at: "",
  },
  {
    id: "3",
    name: "Gdansk Motorsport Arena",
    latitude: 54.352,
    longitude: 18.6466,
    created_at: "",
  },
  {
    id: "4",
    name: "Wroclaw Speed Park",
    latitude: 51.1079,
    longitude: 17.0385,
    created_at: "",
  },
  {
    id: "5",
    name: "Poznan Racing Complex",
    latitude: 52.4064,
    longitude: 16.9252,
    created_at: "",
  },
  {
    id: "6",
    name: "Katowice Drift Zone",
    latitude: 50.2649,
    longitude: 19.0238,
    created_at: "",
  },
];

const mockEventTitles = [
  "Warsaw Drift Championship",
  "Beginner Drift Workshop",
  "Street Drift Meetup",
  "Professional Drift Competition",
  "Night Drift Session",
  "Drift Training Camp",
  "Amateur Drift Contest",
  "Drift Skills Challenge",
  "Weekend Drift Practice",
  "Advanced Drift Techniques",
  "Drift Car Show & Competition",
  "Rookie Drift Experience",
  "Sunset Drift Session",
  "Winter Drift Challenge",
  "Spring Drift Festival",
  "Summer Drift Series",
  "Autumn Drift Cup",
  "Urban Drift Experience",
  "Mountain Drift Adventure",
  "Coastal Drift Rally",
];

const mockDescriptions = [
  "Join us for an exciting drift competition featuring drivers from across the region.",
  "Perfect for beginners looking to learn the basics of drifting in a safe environment.",
  "Casual meetup for drift enthusiasts to practice and share techniques.",
  "High-level competition featuring professional drift drivers and modified cars.",
  "Experience the thrill of night drifting under the lights.",
  "Intensive training camp to improve your drifting skills.",
  "Amateur-friendly competition with prizes for top performers.",
  "Test your skills in various drift challenges and obstacles.",
  "Relaxed practice session for all skill levels.",
  "Advanced techniques workshop for experienced drifters.",
  "Combine car show with competitive drifting action.",
  "First-time drift experience with professional instruction.",
  "Beautiful sunset backdrop for your drifting experience.",
  "Special winter conditions drift training and competition.",
  "Celebrate spring with our biggest drift festival of the year.",
  "Multi-round summer championship series.",
  "Autumn colors provide the perfect backdrop for drifting.",
  "City-based drift experience in urban environments.",
  "Take your drifting to scenic mountain locations.",
  "Drift by the coast with ocean views.",
];

const mockCreators = [
  { id: "1", display_name: "Alex Kowalski", email: "alex@example.com" },
  { id: "2", display_name: "Maria Nowak", email: "maria@example.com" },
  { id: "3", display_name: "Piotr Wiśniewski", email: "piotr@example.com" },
  { id: "4", display_name: "Anna Wójcik", email: "anna@example.com" },
  { id: "5", display_name: "Tomasz Kowalczyk", email: "tomasz@example.com" },
  {
    id: "6",
    display_name: "Katarzyna Lewandowska",
    email: "katarzyna@example.com",
  },
  { id: "7", display_name: "Michał Zieliński", email: "michal@example.com" },
  {
    id: "8",
    display_name: "Agnieszka Szymańska",
    email: "agnieszka@example.com",
  },
];
